// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzariaMvc.Data;

namespace PizzariaMvc.Migrations
{
    [DbContext(typeof(PizzariaMvcContext))]
    [Migration("20230120005825_PopulandoPizzas")]
    partial class PopulandoPizzas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PizzariaMvc.Models.Cardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Sabor");

                    b.HasKey("Id");

                    b.ToTable("Cardapios");
                });

            modelBuilder.Entity("PizzariaMvc.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Complemento");

                    b.Property<string>("Endereco");

                    b.Property<string>("Nome");

                    b.Property<int>("NumeroEndereco");

                    b.Property<int?>("PedidoId");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PizzariaMvc.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClienteId");

                    b.Property<int>("PizzaId");

                    b.Property<int>("QtdPizzas");

                    b.Property<int>("TamanhoPizza");

                    b.Property<double>("Troco");

                    b.Property<double>("TrocoPara");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("PizzariaMvc.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PedidoId");

                    b.Property<double>("Preco");

                    b.Property<int>("TamanhoPizza");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzariaMvc.Models.Cliente", b =>
                {
                    b.HasOne("PizzariaMvc.Models.Pedido")
                        .WithMany("Clientes")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("PizzariaMvc.Models.Pizza", b =>
                {
                    b.HasOne("PizzariaMvc.Models.Pedido")
                        .WithMany("Pizzas")
                        .HasForeignKey("PedidoId");
                });
#pragma warning restore 612, 618
        }
    }
}
